# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#

required = ["k8s.io/code-generator/cmd/client-gen"]

[prune]
  go-tests = true
  unused-packages = true
  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
  [[prune.project]]
    name = "k8s.io/gengo"
    unused-packages = false

[[constraint]]
  name = "github.com/palantir/k8s-spark-scheduler-lib"
  version = "0.2.9"

[[constraint]]
  version = "kubernetes-1.17.2"
  name = "k8s.io/client-go"

[[constraint]]
  version = "kubernetes-1.17.2"
  name = "k8s.io/apimachinery"

[[constraint]]
  version = "kubernetes-1.17.2"
  name = "k8s.io/apiextensions-apiserver"

[[constraint]]
  version = "v1.1.0"
  name = "github.com/palantir/witchcraft-go-logging"

[[constraint]]
  version = "v1.14.0"
  name = "github.com/palantir/witchcraft-go-server"

[[constraint]]
  version = "v1.3.0"
  name = "github.com/palantir/witchcraft-go-error"

[[constraint]]
  version = "v1.0.1"
  name = "github.com/palantir/pkg"
